version: '3'
services:
  db:
    container_name: db
    image: 'mysql:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 300s
      retries: 10
  api:
    build: .
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=database
      - DB_USER=root
    ports:
      - "127.0.0.1:9010:9010"
